In [11]:
!pip install -q \
  torch \
  peft \
  huggingface_hub \
  ipywidgets

!pip install -U datasets optuna

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.4.1)
Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (4.5.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.20.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (22.0.0)
Requirement already satisfied: dill<0.4.1,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.19 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.10.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.36.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.17.1)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna) (6.10.1)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.44)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (1.3.10)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.15.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (3.13.2)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.11.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2025.10.5)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.2.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.10.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.12/dist-packages (from anyio->httpx<1.0.0->datasets) (1.3.1)
Requirement already satisfied: MarkupSafe>=0.9.2 in /usr/local/lib/python3.12/dist-packages (from Mako->alembic>=1.5.0->optuna) (3.0.3)

In [4]:
import os, shutil, gc, torch, optuna
from huggingface_hub import login, notebook_login, HfFolder, HfApi, hf_hub_download, delete_repo, list_repo_files, snapshot_download
os.environ["TRANSFORMERS_NO_TF"] = "1"   # prevents TF/Keras import
from transformers import (AutoTokenizer, AutoModelForSequenceClassification, BitsAndBytesConfig,
                          Trainer, TrainingArguments, DataCollatorWithPadding, default_data_collator)
from peft import (LoraConfig, get_peft_model, prepare_model_for_kbit_training)
from datasets import load_dataset, concatenate_datasets, Dataset, DatasetDict
import json
import inspect
import pandas as pd
import numpy as np
import tempfile
from datetime import datetime
from collections import Counter
from torch.utils.data import Dataset, Subset

In [5]:
model_name = "distilbert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/483 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [6]:
api = HfApi()
login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [7]:
HF_DATASET_REPO = "eduhuemar001/news"

# Download JSON files from HF dataset repo
train_path = hf_hub_download(
    repo_id=HF_DATASET_REPO,
    filename="train.json",
    repo_type="dataset",
    local_dir=".",
    local_dir_use_symlinks=False
)
eval_path = hf_hub_download(
    repo_id=HF_DATASET_REPO,
    filename="eval.json",
    repo_type="dataset",
    local_dir=".",
    local_dir_use_symlinks=False
)

# Load datasets
with open(train_path, "r", encoding="utf-8") as f:
    dataset_train = json.load(f)

with open(eval_path, "r", encoding="utf-8") as f:
    dataset_eval = json.load(f)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:979: UserWarning: `local_dir_use_symlinks` parameter is deprecated and will be ignored. The process to download files to a local folder has been updated and do not rely on symlinks anymore. You only need to pass a destination folder as`local_dir`.
For more details, check out https://huggingface.co/docs/huggingface_hub/main/en/guides/download#download-files-to-local-folder.
  warnings.warn(

train.json:   0%|          | 0.00/70.9M [00:00<?, ?B/s]

eval.json:   0%|          | 0.00/23.1M [00:00<?, ?B/s]

In [8]:
class NewsPairDataset(Dataset):
    def __init__(self, data, tokenizer, max_length=512):
        self.data = data                  # list of dicts with keys of title, text, status
        self.tok = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.data)

    def __getitem__(self, i):
        item = self.data[i]
        title = (item.get("title") or "").strip()
        text  = (item.get("text")  or "").strip()
        label = int(item.get("status"))   # 0/1

        enc = self.tok(
            text=title,                   # News title
            text_pair=text,               # News article
            truncation="only_second",     # keep full title, truncate only news article
            max_length=self.max_length,
            padding=False,                # let collator pad
            return_attention_mask=True
        )

        out = {
            "input_ids": torch.tensor(enc["input_ids"], dtype=torch.long),
            "attention_mask": torch.tensor(enc["attention_mask"], dtype=torch.long),
            "labels": torch.tensor(label, dtype=torch.long),
        }
        return out

train_dataset = NewsPairDataset(dataset_train, tokenizer, max_length=512)
eval_dataset  = NewsPairDataset(dataset_eval,  tokenizer, max_length=512)

In [13]:
rns = np.random.RandomState(42)
TRAIN_CAP = min(len(train_dataset), 1000)
EVAL_CAP  = min(len(eval_dataset),  200)

train_idx = rns.choice(len(train_dataset), size=TRAIN_CAP, replace=False)
eval_idx  = rns.choice(len(eval_dataset),  size=EVAL_CAP,  replace=False)

train_small = Subset(train_dataset, sorted(train_idx))
eval_small  = Subset(eval_dataset,  sorted(eval_idx))

def objective(trial: optuna.Trial):
    # Hyperparameter search space
    hp = {
        "learning_rate":       trial.suggest_float("learning_rate", 1e-5, 5e-3, log=True),
        "weight_decay":        trial.suggest_float("weight_decay", 0.0, 0.2),
        "warmup_ratio":        trial.suggest_float("warmup_ratio", 0.0, 0.2),
        "lr_scheduler_type":   trial.suggest_categorical("lr_scheduler_type", ["linear", "cosine"]),
        "per_device_train_bs": trial.suggest_categorical("per_device_train_batch_size", [8, 16, 32]),
        "per_device_eval_bs":  trial.suggest_categorical("per_device_eval_batch_size",  [16, 32]),
        "gradient_accum":      trial.suggest_categorical("gradient_accumulation_steps", [1, 2, 4]),
        "num_train_epochs":    trial.suggest_int("num_train_epochs", 2, 6),
    }

    # ----- model -----
    model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=2)
    model = model.to("cuda")
    # print(next(model.parameters()).device)

    args = TrainingArguments(
        output_dir=f"./runs/trial_{trial.number}",
        learning_rate=hp["learning_rate"],
        weight_decay=hp["weight_decay"],
        warmup_ratio=hp["warmup_ratio"],
        lr_scheduler_type=hp["lr_scheduler_type"],
        per_device_train_batch_size=hp["per_device_train_bs"],
        per_device_eval_batch_size=hp["per_device_eval_bs"],
        gradient_accumulation_steps=hp["gradient_accum"],
        num_train_epochs=hp["num_train_epochs"],
        eval_strategy="steps",
        eval_steps=200,
        logging_strategy="steps",
        logging_steps=50,
        save_strategy="no",
        report_to="none",
        fp16=False,
        bf16=False,
        seed=42,
        load_best_model_at_end=False,
        dataloader_num_workers=0,
        optim="adamw_torch",
    )

    trainer = Trainer(
        model=model,
        args=args,
        tokenizer=tokenizer,
        train_dataset=train_small,
        eval_dataset=eval_small,
        data_collator=DataCollatorWithPadding(tokenizer),
    )

    trainer.train()
    metrics = trainer.evaluate()
    score = float(metrics["eval_loss"])

    # cleanup VRAM
    del trainer, model
    torch.cuda.empty_cache()

    return score

In [16]:
HF_REPO = "eduhuemar001/distilbert-news-tuning"
REMOTE_DB_FILE = "optuna_study.db"
LOCAL_DB = f"/content/{REMOTE_DB_FILE}"
STUDY_KEY = f"sqlite:///{LOCAL_DB}"

api = HfApi()

# Try to resume from HF Hub
try:
    db_path = hf_hub_download(
        repo_id=HF_REPO,
        filename=REMOTE_DB_FILE,
        repo_type="model",
        local_dir="/content",
        local_dir_use_symlinks=False
    )
    print(f"Resuming from HF DB at: {db_path}")
except Exception as e:
    print(f"No remote DB found (starting fresh): {e}")
    # Ensure local path exists, Optuna db be created
    if not os.path.exists(LOCAL_DB):
        open(LOCAL_DB, "wb").close()

# Create or resume study using the local SQLite file
study = optuna.create_study(
    study_name="distilbert_hpo",
    direction="minimize",
    storage=STUDY_KEY,
    load_if_exists=True
)

# 3) Callback: upload updated DB to HF after each trial
def upload_db_after_trial(study, trial):
    api.upload_file(
        path_or_fileobj=LOCAL_DB,
        path_in_repo=REMOTE_DB_FILE,
        repo_id=HF_REPO,
        repo_type="model",
        commit_message=f"Optuna DB update after trial {trial.number}"
    )
    print(f"Pushed DB after trial {trial.number}")

# 4) Run optimization (writes to SQLite every trial; then uploads)
study.optimize(objective, n_trials=20, callbacks=[upload_db_after_trial])

print("Best params:", study.best_trial.params)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/file_download.py:979: UserWarning: `local_dir_use_symlinks` parameter is deprecated and will be ignored. The process to download files to a local folder has been updated and do not rely on symlinks anymore. You only need to pass a destination folder as`local_dir`.
For more details, check out https://huggingface.co/docs/huggingface_hub/main/en/guides/download#download-files-to-local-folder.
  warnings.warn(
[I 2025-11-09 18:19:17,771] Using an existing study with name 'distilbert_hpo' instead of creating a new one.

No remote DB found (starting fresh): 404 Client Error. (Request ID: Root=1-6910db25-2fcd86f43ff24aab3e124cd4;223ecd52-8d39-4b08-9a4e-e398c9b51d64)

Entry Not Found for url: https://huggingface.co/eduhuemar001/distilbert-news-tuning/resolve/main/optuna_study.db.

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/tmp/ipython-input-1510381963.py:53: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2025-11-09 18:24:11,743] Trial 4 finished with value: 0.00022262363927438855 and parameters: {'learning_rate': 0.0002111577160148881, 'weight_decay': 0.14170474728616472, 'warmup_ratio': 0.15983285501618702, 'lr_scheduler_type': 'cosine', 'per_device_train_batch_size': 8, 'per_device_eval_batch_size': 16, 'gradient_accumulation_steps': 4, 'num_train_epochs': 6}. Best is trial 4 with value: 0.00022262363927438855.

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  /content/optuna_study.db    : 100%|##########|  123kB /  123kB

Pushed DB after trial 4

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/tmp/ipython-input-1510381963.py:53: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2025-11-09 18:28:21,436] Trial 5 finished with value: 0.000796162465121597 and parameters: {'learning_rate': 0.0002237780168342242, 'weight_decay': 0.021069296635472724, 'warmup_ratio': 0.1397576221828322, 'lr_scheduler_type': 'cosine', 'per_device_train_batch_size': 32, 'per_device_eval_batch_size': 16, 'gradient_accumulation_steps': 4, 'num_train_epochs': 5}. Best is trial 4 with value: 0.00022262363927438855.

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  /content/optuna_study.db    : 100%|##########|  123kB /  123kB

Pushed DB after trial 5

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/tmp/ipython-input-1510381963.py:53: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2025-11-09 18:33:16,860] Trial 6 finished with value: 0.00028599731740541756 and parameters: {'learning_rate': 0.00010286970947532485, 'weight_decay': 0.099831276407709, 'warmup_ratio': 0.14581562253853272, 'lr_scheduler_type': 'cosine', 'per_device_train_batch_size': 8, 'per_device_eval_batch_size': 16, 'gradient_accumulation_steps': 4, 'num_train_epochs': 6}. Best is trial 4 with value: 0.00022262363927438855.

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  /content/optuna_study.db    : 100%|##########|  123kB /  123kB

Pushed DB after trial 6

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/tmp/ipython-input-1510381963.py:53: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2025-11-09 18:36:40,675] Trial 7 finished with value: 0.000497677712701261 and parameters: {'learning_rate': 5.2150441000753866e-05, 'weight_decay': 0.09643129564497217, 'warmup_ratio': 0.19470166549797163, 'lr_scheduler_type': 'linear', 'per_device_train_batch_size': 8, 'per_device_eval_batch_size': 32, 'gradient_accumulation_steps': 2, 'num_train_epochs': 4}. Best is trial 4 with value: 0.00022262363927438855.

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  /content/optuna_study.db    : 100%|##########|  123kB /  123kB

Pushed DB after trial 7

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/tmp/ipython-input-1510381963.py:53: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2025-11-09 18:40:51,846] Trial 8 finished with value: 0.0006301177782006562 and parameters: {'learning_rate': 0.00035911526860446736, 'weight_decay': 0.05064136882638675, 'warmup_ratio': 0.18877363640176287, 'lr_scheduler_type': 'linear', 'per_device_train_batch_size': 16, 'per_device_eval_batch_size': 16, 'gradient_accumulation_steps': 4, 'num_train_epochs': 5}. Best is trial 4 with value: 0.00022262363927438855.

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  /content/optuna_study.db    : 100%|##########|  127kB /  127kB

Pushed DB after trial 8

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/tmp/ipython-input-1510381963.py:53: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2025-11-09 18:44:14,900] Trial 9 finished with value: 0.0012799841351807117 and parameters: {'learning_rate': 0.00010021483107127476, 'weight_decay': 0.023171031547366286, 'warmup_ratio': 0.13261031658918426, 'lr_scheduler_type': 'cosine', 'per_device_train_batch_size': 32, 'per_device_eval_batch_size': 32, 'gradient_accumulation_steps': 1, 'num_train_epochs': 4}. Best is trial 4 with value: 0.00022262363927438855.

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  /content/optuna_study.db    : 100%|##########|  127kB /  127kB

Pushed DB after trial 9

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/tmp/ipython-input-1510381963.py:53: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2025-11-09 18:48:27,214] Trial 10 finished with value: 0.6895741820335388 and parameters: {'learning_rate': 0.003291112288849685, 'weight_decay': 0.06344859155226293, 'warmup_ratio': 0.11820754124776267, 'lr_scheduler_type': 'linear', 'per_device_train_batch_size': 16, 'per_device_eval_batch_size': 16, 'gradient_accumulation_steps': 1, 'num_train_epochs': 5}. Best is trial 4 with value: 0.00022262363927438855.

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  /content/optuna_study.db    : 100%|##########|  127kB /  127kB

Pushed DB after trial 10

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/tmp/ipython-input-1510381963.py:53: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2025-11-09 18:53:25,154] Trial 11 finished with value: 0.00037703319685533643 and parameters: {'learning_rate': 0.0002999306944693399, 'weight_decay': 0.07228313765993237, 'warmup_ratio': 0.057765287154276534, 'lr_scheduler_type': 'cosine', 'per_device_train_batch_size': 32, 'per_device_eval_batch_size': 32, 'gradient_accumulation_steps': 4, 'num_train_epochs': 6}. Best is trial 4 with value: 0.00022262363927438855.

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  /content/optuna_study.db    : 100%|##########|  127kB /  127kB

Pushed DB after trial 11

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/tmp/ipython-input-1510381963.py:53: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2025-11-09 18:58:26,222] Trial 12 finished with value: 0.6907373070716858 and parameters: {'learning_rate': 0.0012950594102580381, 'weight_decay': 0.06855660626740445, 'warmup_ratio': 0.18320552188964215, 'lr_scheduler_type': 'cosine', 'per_device_train_batch_size': 16, 'per_device_eval_batch_size': 32, 'gradient_accumulation_steps': 1, 'num_train_epochs': 6}. Best is trial 4 with value: 0.00022262363927438855.

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  /content/optuna_study.db    : 100%|##########|  131kB /  131kB

Pushed DB after trial 12

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/tmp/ipython-input-1510381963.py:53: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2025-11-09 19:00:09,491] Trial 13 finished with value: 0.08190213143825531 and parameters: {'learning_rate': 1.0662029148842777e-05, 'weight_decay': 0.1611050613529843, 'warmup_ratio': 0.076565556523081, 'lr_scheduler_type': 'linear', 'per_device_train_batch_size': 8, 'per_device_eval_batch_size': 16, 'gradient_accumulation_steps': 2, 'num_train_epochs': 2}. Best is trial 4 with value: 0.00022262363927438855.

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  /content/optuna_study.db    : 100%|##########|  131kB /  131kB

Pushed DB after trial 13

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/tmp/ipython-input-1510381963.py:53: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2025-11-09 19:01:52,034] Trial 14 finished with value: 0.009975288063287735 and parameters: {'learning_rate': 4.4754653483611515e-05, 'weight_decay': 0.13790456425443645, 'warmup_ratio': 0.15427691092174292, 'lr_scheduler_type': 'cosine', 'per_device_train_batch_size': 8, 'per_device_eval_batch_size': 16, 'gradient_accumulation_steps': 4, 'num_train_epochs': 2}. Best is trial 4 with value: 0.00022262363927438855.

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  /content/optuna_study.db    : 100%|##########|  131kB /  131kB

Pushed DB after trial 14

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/tmp/ipython-input-1510381963.py:53: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2025-11-09 19:04:21,977] Trial 15 finished with value: 0.0018633544677868485 and parameters: {'learning_rate': 9.366726499945413e-05, 'weight_decay': 0.12215217297321902, 'warmup_ratio': 0.09957044691988712, 'lr_scheduler_type': 'cosine', 'per_device_train_batch_size': 8, 'per_device_eval_batch_size': 16, 'gradient_accumulation_steps': 4, 'num_train_epochs': 3}. Best is trial 4 with value: 0.00022262363927438855.

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  /content/optuna_study.db    : 100%|##########|  131kB /  131kB

Pushed DB after trial 15

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/tmp/ipython-input-1510381963.py:53: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2025-11-09 19:09:16,719] Trial 16 finished with value: 0.004277779720723629 and parameters: {'learning_rate': 1.644502257670184e-05, 'weight_decay': 0.1092309529812569, 'warmup_ratio': 0.16110504762920855, 'lr_scheduler_type': 'cosine', 'per_device_train_batch_size': 8, 'per_device_eval_batch_size': 16, 'gradient_accumulation_steps': 4, 'num_train_epochs': 6}. Best is trial 4 with value: 0.00022262363927438855.

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  /content/optuna_study.db    : 100%|##########|  135kB /  135kB

Pushed DB after trial 16

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/tmp/ipython-input-1510381963.py:53: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2025-11-09 19:13:22,215] Trial 17 finished with value: 0.05832689255475998 and parameters: {'learning_rate': 0.0010457477335555968, 'weight_decay': 0.1478331012210259, 'warmup_ratio': 0.10157416919641866, 'lr_scheduler_type': 'cosine', 'per_device_train_batch_size': 8, 'per_device_eval_batch_size': 16, 'gradient_accumulation_steps': 4, 'num_train_epochs': 5}. Best is trial 4 with value: 0.00022262363927438855.

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  /content/optuna_study.db    : 100%|##########|  135kB /  135kB

Pushed DB after trial 17

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/tmp/ipython-input-1510381963.py:53: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2025-11-09 19:16:40,369] Trial 18 finished with value: 0.0005940643022768199 and parameters: {'learning_rate': 0.000127695075781926, 'weight_decay': 0.1944590983818724, 'warmup_ratio': 0.16657069501909783, 'lr_scheduler_type': 'cosine', 'per_device_train_batch_size': 8, 'per_device_eval_batch_size': 16, 'gradient_accumulation_steps': 4, 'num_train_epochs': 4}. Best is trial 4 with value: 0.00022262363927438855.

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  /content/optuna_study.db    : 100%|##########|  143kB /  143kB

Pushed DB after trial 18

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/tmp/ipython-input-1510381963.py:53: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2025-11-09 19:21:40,980] Trial 19 finished with value: 0.00090974778868258 and parameters: {'learning_rate': 3.1295385911497695e-05, 'weight_decay': 0.0890582080927241, 'warmup_ratio': 0.12122017551662351, 'lr_scheduler_type': 'cosine', 'per_device_train_batch_size': 8, 'per_device_eval_batch_size': 16, 'gradient_accumulation_steps': 2, 'num_train_epochs': 6}. Best is trial 4 with value: 0.00022262363927438855.

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  /content/optuna_study.db    : 100%|##########|  143kB /  143kB

Pushed DB after trial 19

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/tmp/ipython-input-1510381963.py:53: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2025-11-09 19:25:46,660] Trial 20 finished with value: 0.03468254953622818 and parameters: {'learning_rate': 0.0008102503627991931, 'weight_decay': 0.1258451369599852, 'warmup_ratio': 0.0008929408640933334, 'lr_scheduler_type': 'cosine', 'per_device_train_batch_size': 8, 'per_device_eval_batch_size': 16, 'gradient_accumulation_steps': 4, 'num_train_epochs': 5}. Best is trial 4 with value: 0.00022262363927438855.

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  /content/optuna_study.db    : 100%|##########|  147kB /  147kB

Pushed DB after trial 20

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/tmp/ipython-input-1510381963.py:53: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2025-11-09 19:30:41,304] Trial 21 finished with value: 0.009673620574176311 and parameters: {'learning_rate': 0.00013876033681236303, 'weight_decay': 0.16567589880825384, 'warmup_ratio': 0.14670687871137167, 'lr_scheduler_type': 'linear', 'per_device_train_batch_size': 8, 'per_device_eval_batch_size': 16, 'gradient_accumulation_steps': 4, 'num_train_epochs': 6}. Best is trial 4 with value: 0.00022262363927438855.

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  /content/optuna_study.db    : 100%|##########|  147kB /  147kB

  /content/optuna_study.db    : 100%|##########|  147kB /  147kB

Pushed DB after trial 21

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/tmp/ipython-input-1510381963.py:53: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2025-11-09 19:33:12,481] Trial 22 finished with value: 0.025641417130827904 and parameters: {'learning_rate': 0.0005706818688095693, 'weight_decay': 0.10775883257494402, 'warmup_ratio': 0.17219813273095813, 'lr_scheduler_type': 'cosine', 'per_device_train_batch_size': 32, 'per_device_eval_batch_size': 16, 'gradient_accumulation_steps': 2, 'num_train_epochs': 3}. Best is trial 4 with value: 0.00022262363927438855.

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  /content/optuna_study.db    : 100%|##########|  147kB /  147kB

Pushed DB after trial 22

Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/tmp/ipython-input-1510381963.py:53: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

[I 2025-11-09 19:36:29,628] Trial 23 finished with value: 0.6871696710586548 and parameters: {'learning_rate': 0.0017078266244985958, 'weight_decay': 0.14580427496913684, 'warmup_ratio': 0.09051339748513235, 'lr_scheduler_type': 'cosine', 'per_device_train_batch_size': 8, 'per_device_eval_batch_size': 16, 'gradient_accumulation_steps': 4, 'num_train_epochs': 4}. Best is trial 4 with value: 0.00022262363927438855.

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  /content/optuna_study.db    : 100%|##########|  147kB /  147kB

Pushed DB after trial 23
Best params: {'learning_rate': 0.0002111577160148881, 'weight_decay': 0.14170474728616472, 'warmup_ratio': 0.15983285501618702, 'lr_scheduler_type': 'cosine', 'per_device_train_batch_size': 8, 'per_device_eval_batch_size': 16, 'gradient_accumulation_steps': 4, 'num_train_epochs': 6}